#!/bin/sh

# remove backup files
find . -name "*~" | xargs rm -f

# remove object files
find src -name "*.o" | xargs rm -f
find src -name "*.a" | xargs rm -f
find src -name "*.so" | xargs rm -f

# remove files built by autoconf
rm -rf src/Makevars config.status autom4te.cache config.log

