# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_parse_with_callbacks <- function(text, cmd_action, macro_value_accessor, log_command, debug_level = 0L, echo = 1L) {
    .Call(`_ado_do_parse_with_callbacks`, text, cmd_action, macro_value_accessor, log_command, debug_level, echo)
}

do_parse <- function(text, log_command, debug_level = 0L) {
    .Call(`_ado_do_parse`, text, log_command, debug_level)
}

parse_accept <- function(text) {
    .Call(`_ado_parse_accept`, text)
}

unlockEnvironment <- function(env) {
    .Call(`_ado_unlockEnvironment`, env)
}

